#!/bin/bash
# Downloads and extracts highlight.js by manually querying the official
# download page.
# To change the languages included, modify the `languages` file generated by
# this script on first run.

set -e

url=https://highlightjs.org/download/
tmpzip=highlightjs-TMP.zip
outdir=static/highlightjs
languages=languages

[[ ! -e "$languages" ]] && {
    cat >"$languages" <<EOF
bash
cpp
cs
css
go
ini
java
javascript
json
makefile
markdown
perl
php
python
ruby
rust
sql
xml
EOF
}

csrftoken="$(curl "$url" | grep -Po "(?<=<input type='hidden' name='csrfmiddlewaretoken' value=').{64}")"

data="csrfmiddlewaretoken=$csrftoken"

while read -r lang; do
    data="$data&$lang.js=on"
done <"$languages"

curl "$url" -o "$tmpzip" -H "Referer: $url" -H "Cookie: csrftoken=$csrftoken" --data "$data"

mkdir -p "$outdir"
unzip -o "$tmpzip" highlight.pack.js -d "$outdir"
rm -v "$tmpzip"
